---
version: "3"
services:
  uploader:
    container_name: uploader
    image: eidanyosoy/uploader:latest
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
    security_opt:
      - "apparmor:unconfined"
    volumes:
      - "/opt/appdata/uploader:/config"
      - "/mnt/unionfs:/unionfs:shared"
      - "/mnt/move:/move"
    enviroment:
      - "PUID=${PUID}"
      - "PGID=${PUID}"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.frontend.rule=Host:tracker.example.com"
      - "traefik.port=8080"
    networks:
      - traefik_proxy
    restart: unless-stopped
